services:
  postgres:
    image: postgres:16-alpine
    container_name: taskq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskq
      POSTGRES_PASSWORD: taskq
      POSTGRES_DB: taskq
    ports:
      - "5433:5432"
    volumes:
      - taskq_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskq -d taskq"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  taskq_pg_data: